# Generated by Django 5.2.1 on 2025-05-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='products')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
            ],
        ),
    ]
