# Generated by Django 5.2.1 on 2025-05-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hhoodie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoodie_name', models.CharField(max_length=100)),
                ('hoodie_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('hoodie_description', models.TextField()),
                ('hoodie_image', models.ImageField(upload_to='hoodies')),
            ],
        ),
    ]
