# Generated by Django 5.2.1 on 2025-06-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_working'),
    ]

    operations = [
        migrations.AlterField(
            model_name='working',
            name='working_image',
            field=models.ImageField(upload_to='working_images'),
        ),
    ]
