# Generated by Django 5.0.7 on 2025-06-04 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_working_working_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hhoodie',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='HoodieColorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50)),
                ('color_code', models.CharField(max_length=7)),
                ('color_image', models.ImageField(blank=True, null=True, upload_to='hoodies/colors/')),
                ('hoodie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_options', to='myapp.hhoodie')),
            ],
        ),
    ]
